# @package _global_
task:
  name: pipeline
  stage: "99_pipeline"
  project_name: "${run.clearml.project_root}/${run.clearml.project_layout.solution_root}/${run.clearml.project_layout.pipeline_root_group}/${run.clearml.project_layout.pipeline_runs_group}/${run.usecase_id}"

pipeline:
  run_dataset_register: false
  run_preprocess: true
  run_train: true
  run_train_ensemble: ${ensemble.enabled}
  run_leaderboard: true
  run_infer: false
  plan_only: false
  dry_run: false
  preprocess_variant: null
  preprocess_variants: []
  model_set: regression_all
  model_variants: []
  selection:
    enabled_preprocess_variants: []
    enabled_model_variants: []

  grid:
    preprocess_variants: [stdscaler_ohe]
    model_variants: []
    max_jobs: ${exec_policy.limits.max_jobs}

  hpo:
    enabled: false
    params:
      ridge:
        alpha: [0.1, 1.0, 10.0]
